import "server-only";
import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";

// Local-filesystem document storage. Everything written here is resident PHI,
// so keys are opaque and reads are path-checked against the root. Swapping in
// S3/GCS means reimplementing these four functions and nothing else.

const ROOT = path.resolve(process.env.STORAGE_DIR || "./storage");

const MAX_BYTES = 25 * 1024 * 1024;

/** File types a survey binder realistically needs; anything else is rejected. */
export const ALLOWED_MIME_TYPES = new Set([
  "application/pdf",
  "image/jpeg",
  "image/png",
  "image/heic",
  "image/webp",
  "image/tiff",
  "application/msword",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "application/vnd.ms-excel",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  "text/plain",
]);

const EXTENSION_BY_MIME: Record<string, string> = {
  "application/pdf": ".pdf",
  "image/jpeg": ".jpg",
  "image/png": ".png",
  "image/heic": ".heic",
  "image/webp": ".webp",
  "image/tiff": ".tif",
  "application/msword": ".doc",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document": ".docx",
  "application/vnd.ms-excel": ".xls",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": ".xlsx",
  "text/plain": ".txt",
};

export class StorageError extends Error {}

export function formatBytes(bytes: number | null | undefined): string {
  if (!bytes) return "—";
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(0)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

/**
 * Persist an uploaded file under `homeId/` and return the storage key.
 * The key is random, never derived from user input, so a crafted filename
 * cannot escape the root or collide with another home's document.
 */
export async function saveUpload(
  homeId: string,
  file: File,
): Promise<{ storageKey: string; sizeBytes: number; mimeType: string }> {
  if (file.size === 0) throw new StorageError("That file is empty.");
  if (file.size > MAX_BYTES) {
    throw new StorageError(
      `That file is ${formatBytes(file.size)}. The limit is ${formatBytes(MAX_BYTES)}.`,
    );
  }

  const mimeType = file.type || "application/octet-stream";
  if (!ALLOWED_MIME_TYPES.has(mimeType)) {
    throw new StorageError(
      `${mimeType} files aren't accepted. Upload a PDF, photo, Word, or Excel file.`,
    );
  }

  const ext = EXTENSION_BY_MIME[mimeType] ?? path.extname(file.name).slice(0, 10);
  const storageKey = path.posix.join(homeId, `${crypto.randomUUID()}${ext}`);
  const target = resolveKey(storageKey);

  await fs.mkdir(path.dirname(target), { recursive: true });
  await fs.writeFile(target, Buffer.from(await file.arrayBuffer()));

  return { storageKey, sizeBytes: file.size, mimeType };
}

/** Write generated bytes (e.g. a rendered form) into the vault. */
export async function saveBuffer(
  homeId: string,
  data: Buffer | string,
  extension: string,
): Promise<{ storageKey: string; sizeBytes: number }> {
  const storageKey = path.posix.join(homeId, `${crypto.randomUUID()}${extension}`);
  const target = resolveKey(storageKey);
  await fs.mkdir(path.dirname(target), { recursive: true });
  const buffer = Buffer.isBuffer(data) ? data : Buffer.from(data, "utf8");
  await fs.writeFile(target, buffer);
  return { storageKey, sizeBytes: buffer.byteLength };
}

/** Resolve a key to an absolute path, refusing anything outside the root. */
function resolveKey(storageKey: string): string {
  const target = path.resolve(ROOT, storageKey);
  const rootWithSep = ROOT.endsWith(path.sep) ? ROOT : ROOT + path.sep;
  if (!target.startsWith(rootWithSep)) {
    throw new StorageError("Invalid storage key.");
  }
  return target;
}

export async function readFile(storageKey: string): Promise<Buffer> {
  return fs.readFile(resolveKey(storageKey));
}

export async function deleteFile(storageKey: string): Promise<void> {
  try {
    await fs.unlink(resolveKey(storageKey));
  } catch (err) {
    // A missing file is the desired end state; anything else is real.
    if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
  }
}
