/**
 * The record types an adult family home is generally expected to keep, grouped
 * into the tabs a physical inspection binder usually has.
 *
 * These are descriptions of records, not quotations of rule text. `wacCite`
 * points at the subchapter the record belongs to so a provider knows where to
 * look; it is a navigation aid, not a legal assertion. Renewal intervals are
 * common practice defaults — confirm each against your own licensor's
 * expectations and edit under Settings → Document types.
 */

export type SeedDocumentType = {
  code: string;
  name: string;
  description: string;
  scope: "HOME" | "RESIDENT" | "EMPLOYEE";
  category: string;
  wacCite: string | null;
  renewalMonths: number | null;
  warnDays?: number;
  sortOrder: number;
};

export const SEED_DOCUMENT_TYPES: SeedDocumentType[] = [
  // ---- Home: licensing and insurance ----
  {
    code: "afh_license",
    name: "Adult family home license",
    description: "Your current license certificate as issued by the department.",
    scope: "HOME",
    category: "Licensing",
    wacCite: "WAC 388-76-10005",
    renewalMonths: 12,
    warnDays: 90,
    sortOrder: 10,
  },
  {
    code: "business_license",
    name: "Washington business license",
    description: "State business licence / UBI registration for the operating entity.",
    scope: "HOME",
    category: "Licensing",
    wacCite: "WAC 388-76-10055",
    renewalMonths: 12,
    sortOrder: 20,
  },
  {
    code: "liability_insurance",
    name: "Liability insurance certificate",
    description: "Certificate of insurance showing current coverage and limits.",
    scope: "HOME",
    category: "Licensing",
    wacCite: "WAC 388-76-10191",
    renewalMonths: 12,
    sortOrder: 30,
  },
  {
    code: "seven_eight_bed_approval",
    name: "Seven or eight bed approval",
    description:
      "Documentation supporting a seven or eight bed licence, including any additional conditions imposed.",
    scope: "HOME",
    category: "Licensing",
    wacCite: "WAC 388-76-10031",
    renewalMonths: null,
    sortOrder: 40,
  },

  // ---- Home: safety and emergency ----
  {
    code: "disaster_plan",
    name: "Disaster and emergency preparedness plan",
    description:
      "Written plan covering evacuation, sheltering, utility loss, and resident-specific needs.",
    scope: "HOME",
    category: "Safety and emergency",
    wacCite: "WAC 388-76-10191",
    renewalMonths: 12,
    sortOrder: 50,
  },
  {
    code: "evacuation_drill_log",
    name: "Evacuation drill log",
    description: "Record of practice evacuations, who took part, and how long they took.",
    scope: "HOME",
    category: "Safety and emergency",
    wacCite: "WAC 388-76-10191",
    renewalMonths: 12,
    sortOrder: 60,
  },
  {
    code: "fire_safety_inspection",
    name: "Fire safety inspection",
    description: "Most recent fire authority inspection or smoke alarm / extinguisher service record.",
    scope: "HOME",
    category: "Safety and emergency",
    wacCite: "WAC 388-76-10191",
    renewalMonths: 12,
    sortOrder: 70,
  },
  {
    code: "water_test",
    name: "Water quality test",
    description: "Test results where the home is on a private or shared water supply.",
    scope: "HOME",
    category: "Safety and emergency",
    wacCite: "WAC 388-76-10415",
    renewalMonths: 12,
    sortOrder: 80,
  },

  // ---- Home: operations ----
  {
    code: "policies_procedures",
    name: "Policies and procedures manual",
    description: "The home's written operating policies, including abuse reporting and grievances.",
    scope: "HOME",
    category: "Operations",
    wacCite: "WAC 388-76-10191",
    renewalMonths: 24,
    sortOrder: 90,
  },
  {
    code: "infection_control_plan",
    name: "Infection control plan",
    description: "Written infection prevention and communicable disease procedures.",
    scope: "HOME",
    category: "Operations",
    wacCite: "WAC 388-76-10255",
    renewalMonths: 12,
    sortOrder: 100,
  },
  {
    code: "staffing_schedule",
    name: "Staffing schedule",
    description: "Current schedule showing coverage across all shifts.",
    scope: "HOME",
    category: "Operations",
    wacCite: "WAC 388-76-10191",
    renewalMonths: 3,
    warnDays: 21,
    sortOrder: 110,
  },
  {
    code: "incident_log",
    name: "Incident and injury log",
    description: "Running log of falls, injuries, elopements, and reportable incidents.",
    scope: "HOME",
    category: "Operations",
    wacCite: "WAC 388-76-10191",
    renewalMonths: 12,
    sortOrder: 120,
  },
  {
    code: "specialty_designation",
    name: "Specialty designation approval",
    description:
      "Departmental approval for a dementia, mental health, or developmental disability specialty designation.",
    scope: "HOME",
    category: "Operations",
    wacCite: "WAC 388-76-10495",
    renewalMonths: null,
    sortOrder: 130,
  },
  {
    code: "medicaid_contract",
    name: "Medicaid contract",
    description: "Current contract and rate letter for Medicaid-funded residents.",
    scope: "HOME",
    category: "Operations",
    wacCite: "WAC 388-76-10191",
    renewalMonths: 12,
    sortOrder: 140,
  },

  // ---- Resident records ----
  {
    code: "admission_agreement",
    name: "Admission agreement",
    description: "Signed agreement covering services, rates, and conditions of residency.",
    scope: "RESIDENT",
    category: "Resident records",
    wacCite: "WAC 388-76-10315",
    renewalMonths: null,
    sortOrder: 200,
  },
  {
    code: "disclosure_of_services",
    name: "Disclosure of services",
    description: "Written disclosure of what the home does and does not provide.",
    scope: "RESIDENT",
    category: "Resident records",
    wacCite: "WAC 388-76-10315",
    renewalMonths: null,
    sortOrder: 210,
  },
  {
    code: "resident_rights_ack",
    name: "Resident rights acknowledgement",
    description: "Signed acknowledgement that resident rights were provided and explained.",
    scope: "RESIDENT",
    category: "Resident records",
    wacCite: "WAC 388-76-10510",
    renewalMonths: null,
    sortOrder: 220,
  },
  {
    code: "resident_assessment",
    name: "Resident assessment",
    description: "Current assessment of the resident's needs, preferences, and condition.",
    scope: "RESIDENT",
    category: "Resident records",
    wacCite: "WAC 388-76-10330",
    renewalMonths: 12,
    warnDays: 45,
    sortOrder: 230,
  },
  {
    code: "negotiated_care_plan",
    name: "Negotiated care plan",
    description:
      "The care plan negotiated with the resident and their representative, and the record of its review.",
    scope: "RESIDENT",
    category: "Resident records",
    wacCite: "WAC 388-76-10355",
    renewalMonths: 12,
    warnDays: 45,
    sortOrder: 240,
  },
  {
    code: "physician_orders",
    name: "Physician orders",
    description: "Current orders from the resident's practitioner, including diet and treatment.",
    scope: "RESIDENT",
    category: "Resident records",
    wacCite: "WAC 388-76-10430",
    renewalMonths: 12,
    sortOrder: 250,
  },
  {
    code: "medication_record",
    name: "Medication administration record",
    description: "The current MAR for this resident.",
    scope: "RESIDENT",
    category: "Resident records",
    wacCite: "WAC 388-76-10430",
    renewalMonths: 1,
    warnDays: 10,
    sortOrder: 260,
  },
  {
    code: "med_self_admin_assessment",
    name: "Medication self-administration assessment",
    description:
      "Assessment supporting a resident's ability to self-administer, where that applies.",
    scope: "RESIDENT",
    category: "Resident records",
    wacCite: "WAC 388-76-10430",
    renewalMonths: 12,
    sortOrder: 270,
  },
  {
    code: "nurse_delegation_consent",
    name: "Nurse delegation consent and record",
    description: "Delegation consent, the RN's instructions, and the supervisory visit record.",
    scope: "RESIDENT",
    category: "Resident records",
    wacCite: "WAC 388-76-10430",
    renewalMonths: 3,
    warnDays: 21,
    sortOrder: 280,
  },
  {
    code: "health_care_directive",
    name: "Advance directive / POLST",
    description: "Advance directive, POLST, or documentation that the resident declined one.",
    scope: "RESIDENT",
    category: "Resident records",
    wacCite: "WAC 388-76-10235",
    renewalMonths: null,
    sortOrder: 290,
  },
  {
    code: "resident_tb_screening",
    name: "Resident tuberculosis screening",
    description: "TB screening result on or around admission.",
    scope: "RESIDENT",
    category: "Resident records",
    wacCite: "WAC 388-76-10265",
    renewalMonths: null,
    sortOrder: 300,
  },
  {
    code: "resident_funds_record",
    name: "Resident funds record",
    description: "Accounting of any resident money the home holds or manages.",
    scope: "RESIDENT",
    category: "Resident records",
    wacCite: "WAC 388-76-10510",
    renewalMonths: 12,
    sortOrder: 310,
  },
  {
    code: "dementia_care_plan_addendum",
    name: "Dementia care plan addendum",
    description: "Additional care planning for a resident with a dementia diagnosis.",
    scope: "RESIDENT",
    category: "Resident records",
    wacCite: "WAC 388-76-10495",
    renewalMonths: 12,
    sortOrder: 320,
  },

  // ---- Employee records ----
  {
    code: "background_check",
    name: "Criminal history background check",
    description: "Background check result and the date it cleared.",
    scope: "EMPLOYEE",
    category: "Employee records",
    wacCite: "WAC 388-76-10160",
    renewalMonths: 24,
    warnDays: 90,
    sortOrder: 400,
  },
  {
    code: "employee_tb_screening",
    name: "Tuberculosis screening",
    description: "TB test or screening result for this staff member.",
    scope: "EMPLOYEE",
    category: "Employee records",
    wacCite: "WAC 388-76-10265",
    renewalMonths: 12,
    sortOrder: 410,
  },
  {
    code: "hca_credential",
    name: "Home care aide / nursing assistant credential",
    description: "Current Department of Health credential.",
    scope: "EMPLOYEE",
    category: "Employee records",
    wacCite: "WAC 388-76-10129",
    renewalMonths: 12,
    warnDays: 75,
    sortOrder: 420,
  },
  {
    code: "cpr_first_aid",
    name: "CPR and first aid certification",
    description: "Current CPR and first aid cards.",
    scope: "EMPLOYEE",
    category: "Employee records",
    wacCite: "WAC 388-76-10129",
    renewalMonths: 24,
    sortOrder: 430,
  },
  {
    code: "hiv_aids_training",
    name: "HIV/AIDS training",
    description: "Certificate of the required bloodborne pathogens / HIV-AIDS training.",
    scope: "EMPLOYEE",
    category: "Employee records",
    wacCite: "WAC 388-76-10129",
    renewalMonths: null,
    sortOrder: 440,
  },
  {
    code: "food_worker_card",
    name: "Food worker card",
    description: "Current food worker card for anyone handling food.",
    scope: "EMPLOYEE",
    category: "Employee records",
    wacCite: "WAC 388-76-10415",
    renewalMonths: 24,
    sortOrder: 450,
  },
  {
    code: "orientation_record",
    name: "Orientation and safety training record",
    description: "Signed record of orientation completed before or at the start of work.",
    scope: "EMPLOYEE",
    category: "Employee records",
    wacCite: "WAC 388-76-10129",
    renewalMonths: null,
    sortOrder: 460,
  },
  {
    code: "continuing_education",
    name: "Continuing education record",
    description: "Annual continuing education hours completed.",
    scope: "EMPLOYEE",
    category: "Employee records",
    wacCite: "WAC 388-76-10129",
    renewalMonths: 12,
    sortOrder: 470,
  },
  {
    code: "job_description_signed",
    name: "Signed job description",
    description: "Job description acknowledged by the employee.",
    scope: "EMPLOYEE",
    category: "Employee records",
    wacCite: "WAC 388-76-10191",
    renewalMonths: null,
    sortOrder: 480,
  },
  {
    code: "specialty_dementia_training",
    name: "Dementia specialty training",
    description: "Specialty training required where the home holds a dementia designation.",
    scope: "EMPLOYEE",
    category: "Employee records",
    wacCite: "WAC 388-76-10495",
    renewalMonths: null,
    sortOrder: 490,
  },
  {
    code: "specialty_mh_training",
    name: "Mental health specialty training",
    description: "Specialty training required where the home holds a mental health designation.",
    scope: "EMPLOYEE",
    category: "Employee records",
    wacCite: "WAC 388-76-10495",
    renewalMonths: null,
    sortOrder: 500,
  },
  {
    code: "specialty_dd_training",
    name: "Developmental disabilities specialty training",
    description:
      "Specialty training required where the home holds a developmental disabilities designation.",
    scope: "EMPLOYEE",
    category: "Employee records",
    wacCite: "WAC 388-76-10495",
    renewalMonths: null,
    sortOrder: 510,
  },
  {
    code: "nurse_delegation_training",
    name: "Nurse delegation training",
    description: "Core nurse delegation training for caregivers accepting delegated tasks.",
    scope: "EMPLOYEE",
    category: "Employee records",
    wacCite: "WAC 388-76-10430",
    renewalMonths: null,
    sortOrder: 520,
  },
];
