import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { runDigestsAction } from "@/app/actions/subscriptions";
import { formatDate } from "@/lib/dates";
import { Badge, Card, EmptyState, ErrorBanner, NoticeBanner, PageHeader } from "@/components/ui";

export const dynamic = "force-dynamic";

/**
 * Everything the platform would have emailed. With no SMTP transport wired up,
 * this is where confirmation links, signing links, and digests land — visible
 * rather than silently dropped.
 */
export default async function OutboxPage({
  searchParams,
}: {
  searchParams: Promise<{ error?: string; ran?: string; sent?: string; skipped?: string; generated?: string }>;
}) {
  const user = await requireUser();
  const params = await searchParams;

  const messages = await prisma.outboxMessage.findMany({
    orderBy: { createdAt: "desc" },
    take: 30,
  });

  return (
    <>
      <PageHeader
        title="Outbox"
        description="No mail transport is configured, so every message the platform generates is queued here instead of being delivered. Implement the transport in src/lib/mailer.ts to send for real."
        action={
          user.role === "ADMIN" ? (
            <form action={runDigestsAction}>
              <button type="submit" className="btn-primary">
                Run due digests
              </button>
            </form>
          ) : undefined
        }
      />

      <ErrorBanner message={params.error} />
      {params.ran && (
        <NoticeBanner
          message={`Digest run complete: ${params.sent ?? 0} queued, ${params.skipped ?? 0} skipped (not due, or nothing to report).`}
        />
      )}
      {params.generated && <NoticeBanner message="Digest generated and queued below." />}

      {messages.length === 0 ? (
        <Card>
          <EmptyState
            title="Nothing queued"
            description="Subscribe to the newsletter or send a signing request and the message will appear here."
          />
        </Card>
      ) : (
        <div className="space-y-5">
          {messages.map((message) => (
            <Card key={message.id}>
              <div className="flex flex-wrap items-center justify-between gap-2">
                <div>
                  <p className="font-semibold text-slate-900">{message.subject}</p>
                  <p className="text-xs text-slate-500">
                    To {message.toEmail} · {formatDate(message.createdAt)}
                  </p>
                </div>
                <div className="flex gap-2">
                  <Badge tone="slate">{message.kind}</Badge>
                  <Badge
                    tone={
                      message.status === "SENT"
                        ? "emerald"
                        : message.status === "FAILED"
                          ? "red"
                          : "amber"
                    }
                  >
                    {message.status}
                  </Badge>
                </div>
              </div>

              {message.error && (
                <p className="mt-2 text-sm text-red-700">{message.error}</p>
              )}

              {/* Bodies are generated by emailLayout/buildDigest, which escape
                  every interpolated value before assembling the markup. */}
              <div className="mt-4 overflow-x-auto rounded-lg border border-slate-200 bg-slate-50 p-4">
                <div
                  className="prose-sm max-w-none text-sm"
                  dangerouslySetInnerHTML={{ __html: message.bodyHtml }}
                />
              </div>
            </Card>
          ))}
        </div>
      )}
    </>
  );
}
